require("config.monitors")
require("config.animations")
require("config.autostart")
require("config.binds")
require("config.colors")
require("config.decorations")
require("config.environment")
require("config.inputs")
require("config.misc")
require("config.variables")
require("config.windowrules")
require("config.workspaces")

-- For Noctalia Color templates
require("noctalia").apply_theme()
