color0 #371b25
color1 #f13275
color2 #f25a90
color3 #f05b42
color4 #5b87d7
color5 #f689af
color6 #f69889
color7 #f3f2f2
color8 #716267
color9 #f13275
color10 #f25a90
color11 #f05b42
color12 #5b87d7
color13 #f689af
color14 #f69889
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #29141c
background            #29141c
foreground            #f3f2f2
selection_foreground  #b6afb1
selection_background  #371b25
active_border_color   #f25a90
inactive_border_color #371b25
url_color             #f25a90

active_tab_foreground   #25181d
active_tab_background   #f25a90
inactive_tab_foreground #b6afb1
inactive_tab_background #371b25
cursor_trail_color      #b6afb1
